### PR TITLE
Preparation for IPv6 support

### PR DESCRIPTION
**Pull request by HeMan**
- Was ip_addr_t, changed it to IPAddress which has support for IPv6 by using operator overloading and such.

### CODE REVIEW

**Comment by HeMan** [comment]
@jesserockz Anything I could do to help here? Add some tests?

**Comment by jesserockz** [comment]
Just closed/reopened to get CI to run. Seems I didnt enable it on this repo.

**Comment by HeMan** [comment]
> Just closed/reopened to get CI to run. Seems I didnt enable it on this repo.

Seem to have failed.

**Comment by jesserockz** [comment]
I have no idea whats going on with the CI actions in this repo...

**Review by jesserockz — APPROVED** [review]

**Pull request merged**
